In [3]:
#creating clinical_comparisons table in mysql

import mysql.connector
import csv
# Replace the placeholders with your MySQL connection details
connection = mysql.connector.connect(
    host='localhost',
    user='root',
    password='root',
   
)


# Replace 'your_database' with the name of the database you created
connection.database = 'clinical_data'
csv_file_path = "C:/Users/akhil/OneDrive/Desktop/clinical_data comparisons.csv"

with open(csv_file_path, 'r', encoding='utf-8') as file:
    csv_data = csv.reader(file)
    header = next(csv_data)

    create_table_query = "CREATE TABLE clinical_comparisons ("
    for column_name in header:
        create_table_query += f"`{column_name}` TEXT, "
    create_table_query = create_table_query[:-2]  # Remove the trailing comma and space
    create_table_query += ")"

    cursor = connection.cursor()
    cursor.execute("DROP TABLE IF EXISTS clinical_comparisons")
    cursor.execute(create_table_query)

    insert_query = f"INSERT INTO clinical_comparisons ({', '.join(['`'+col+'`' for col in header])}) VALUES ({', '.join(['%s'] * len(header))})"

    for row in csv_data:
        cursor.execute(insert_query, row)

    # Commit the changes to the database
    connection.commit()

    cursor.close()

# Close the connection to the MySQL server
connection.close()

In [12]:
# creating the join with multiple primary and secondary_id into result.csv

import csv
import mysql.connector

# Establish a MySQL connection
connection = mysql.connector.connect(
    host='localhost',
    user='root',
    password='root',
    database = 'clinical_data'
)


# Replace 'your_database' with the name of the database you created

# Create a cursor object
cursor = connection.cursor()

# Execute the SQL query
query = """
    SELECT *
    FROM clinical_comparisons AS t
    INNER JOIN all_clinical_files AS o ON t.Primary_id = o.Clinical_Trial_ID
    INNER JOIN all_clinical_files AS d ON t.secondary_id = d.Clinical_Trial_ID
"""
cursor.execute(query)

# Fetch all the rows from the result
rows = cursor.fetchall()

# Define the CSV file path
csv_file_path = 'C:/Users/akhil/OneDrive/Desktop/result.csv'

# Write the rows to the CSV file
with open(csv_file_path, 'w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow([desc[0] for desc in cursor.description])  # Write the header
    writer.writerows(rows)  # Write the rows


# Close the cursor and connection
cursor.close()
connection.close()

In [13]:
#Appending all Single type files with the result.csv

import csv
import mysql.connector

# Establish a MySQL connection
connection = mysql.connector.connect(
    host='localhost',
    user='root',
    password='root',
    database = 'clinical_data'
)


# Create a cursor object
cursor = connection.cursor()

# Execute the SQL query
query = """
    SELECT *
    FROM clinical_comparisons AS t
    INNER JOIN all_clinical_files AS o ON t.Primary_id = o.Clinical_Trial_ID
    WHERE t.com_type = 'Single'
"""
cursor.execute(query)

# Fetch all the rows from the result
rows = cursor.fetchall()

# Define the CSV file path
csv_file_path = 'C:/Users/akhil/OneDrive/Desktop/result.csv'

# Write the rows to the CSV file with UTF-8 encoding
with open(csv_file_path, 'a', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow([desc[0] for desc in cursor.description])  # Write the header
    writer.writerows(rows)  # Write the rows

# Close the cursor and connection
cursor.close()
connection.close()

In [1]:
#insert all the combined data in combine_data table
import csv
import mysql.connector

# Establish a MySQL connection
connection = mysql.connector.connect(
    host='localhost',
    user='root',
    password='root',
    database = 'clinical_data'
)

connection.database = 'clinical_data'
csv_file_path = "C:/Users/akhil/OneDrive/Desktop/result.csv"

with open(csv_file_path, 'r', encoding='utf-8') as file:
    csv_data = csv.reader(file)
    header = next(csv_data)

    create_table_query = "CREATE TABLE combine_data ("
    for column_name in header:
        create_table_query += f"`{column_name}` TEXT, "
    create_table_query = create_table_query[:-2]  # Remove the trailing comma and space
    create_table_query += ")"

    cursor = connection.cursor()
    cursor.execute("DROP TABLE IF EXISTS combine_data")
    cursor.execute(create_table_query)

    insert_query = f"INSERT INTO combine_data ({', '.join(['`'+col+'`' for col in header])}) VALUES ({', '.join(['%s'] * len(header))})"

    for row in csv_data:
        cursor.execute(insert_query, row)

    # Commit the changes to the database
    connection.commit()

    cursor.close()

# Close the connection to the MySQL server
connection.close()

C:\Users\akhil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

DatabaseError: Execution failed on sql '
SELECT *
FROM your_table
': 1146 (42S02): Table 'clinical_data.your_table' doesn't exist